### ISSUE TITLE
Blocks glitch into eache other on fast down

### ISSUE THREAD

**Issue by j0ch3m01** [j0ch3m01/Tetris01#1]

**Comment by JoshuaHernandezMartinez** [comment]
I was about to point it out. Really nice what you're doing with this, hope you get it to a good level.
If I'm not mistaken you based your tetris on my tutorial so I'm really honored for that, back then when I made it I was doing the same as you which is learning how to code. I'll be aware of what you do with this.
keep it up and good luck ;)

**Comment by j0ch3m01** [comment]
@JoshuaHernandezMartinez Yes. I used your code to make this game. Because my level in coding java got beter, I fully remade the hole game. Now I am using another repository for it, so here is a link to it. I will bring out asap an release. [https://github.com/Ice-Eclipse/tetris01](url)

**Comment by j0ch3m01** [comment]
Issue is fixed in the next version.
